# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rust-hyperscan
email: flier.lu@gmail.com
description: > 
 Hyperscan bindings for Rust with Multiple Pattern and Streaming Scan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://flier.github.io/rust-hyperscan/" 
twitter_username: flier_lu
github_username:  flier

# Build settings
markdown: kramdown
